parameters:
    database_driver: pdo_pgsql
    database_host: 127.0.0.1
    database_port: '5433'
    database_name: symfony
    database_user: postgres
    database_password: postgres
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 8df7387b28724d30681746724ab10165c
    database_path: null
