security:
    firewalls:
        admin: 
            pattern: ^/admin
            http_basic: ~
        secured_area:
            pattern:    ^/
            anonymous:  ~
            form_login:
                login_path:  /login
                check_path:  /check
            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/perfil        , roles: ROLE_USER }
        - { path: ^/me-apunto-a-* , roles: ROLE_USER }
        - { path: ^/admin         , roles: ROLE_ADMIN }
        - { path: ^/registro      , roles: IS_AUTHENTICATED_ANONYMOUSLY }

    providers:
        in_memory:
            memory:
                users:
                    ryan:  { password: ryanpass, roles: 'ROLE_USER' }
                    admin: { password: 1234, roles: 'ROLE_ADMIN' }
        main:
            entity: 
             class: Desymfony\DesymfonyBundle\Entity\Usuario
             property: email 

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Desymfony\DesymfonyBundle\Entity\Usuario:  sha512